version: "3"
services:
  server1:
    build: .
    environment:
      - OTHER_SERVER_ADDRESS=http://docker.for.mac.host.internal
      - OTHER_SERVER_PORT=4002
    ports:
      - "4001:3000"
      - "4003:4000"
  server2:
    build: .
    environment:
      - OTHER_SERVER_ADDRESS=http://docker.for.mac.host.internal
      - OTHER_SERVER_PORT=4003
    ports:
      - "4004:3000"
      - "4002:4000"
